package Police_Department_design;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class criminal_details extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    

    /**
     * Creates new form criminal_details
     */
    public criminal_details() {
        initComponents();
        fetch();
       
       }
   public void fetch(){
   PreparedStatement pst;
   try{
    String q;
       q = "select * from criminal_db";
      pst = Get_CNX.getConnection().prepareStatement(q);
    rs=pst.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
   }catch(SQLException ex){
   JOptionPane.showMessageDialog(null,ex);
   }
   
   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField_cid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_ccrime = new javax.swing.JTextField();
        jTextField_age = new javax.swing.JTextField();
        jTextField_conno = new javax.swing.JTextField();
        jTextField_cname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButton_Criminal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_addr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Police_Department_design/Close.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 660, 115, 49));

        jTextField_cid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_cid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cidActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 65, 213, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Criminal name:");
        jLabel2.setPreferredSize(new java.awt.Dimension(125, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 133, 138, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Crime:");
        jLabel3.setPreferredSize(new java.awt.Dimension(125, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 193, 117, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Criminal id:");
        jLabel4.setPreferredSize(new java.awt.Dimension(125, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 63, 117, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Contact num:");
        jLabel5.setPreferredSize(new java.awt.Dimension(125, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 315, 138, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Age:");
        jLabel6.setPreferredSize(new java.awt.Dimension(125, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 252, 87, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Crime Details:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 490, -1, 32));

        jTextField_ccrime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_ccrime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_ccrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ccrimeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_ccrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 195, 213, 37));

        jTextField_age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_age.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ageActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 254, 213, 37));

        jTextField_conno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_conno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_conno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_connoActionPerformed(evt);
            }
        });
        jTextField_conno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_connoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_conno, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 317, 213, 37));

        jTextField_cname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_cname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 133, 213, 37));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 490, 210, 120));

        jButton_Criminal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Criminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Police_Department_design/add new patient.png"))); // NOI18N
        jButton_Criminal.setText("Add Criminal");
        jButton_Criminal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_Criminal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Criminal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CriminalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CriminalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CriminalMouseExited(evt);
            }
        });
        jButton_Criminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CriminalActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Criminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 190, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address:");
        jLabel8.setPreferredSize(new java.awt.Dimension(125, 40));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 396, 116, 38));

        jTextField_addr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_addr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addrActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 397, 213, 37));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("CRIMINAL DETAILS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 580, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cidActionPerformed

    private void jTextField_ccrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ccrimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ccrimeActionPerformed

    private void jTextField_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ageActionPerformed

    private void jTextField_connoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_connoActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_connoActionPerformed

    private void jTextField_cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cnameActionPerformed

    private void jButton_CriminalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CriminalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CriminalMouseClicked

    private void jButton_CriminalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CriminalMouseEntered
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CriminalMouseEntered

    private void jButton_CriminalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CriminalMouseExited
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CriminalMouseExited

    private void jButton_CriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CriminalActionPerformed
        String cid = jTextField_cid.getText();
        String cname = jTextField_cname.getText();
       String crime = jTextField_ccrime.getText();
       String age = jTextField_age.getText();

       String phone = jTextField_conno.getText();
       String address = jTextField_addr.getText();
       String cd = jTextArea.getText();

        // check if the data are empty
        if(verifyFields())
        {
           
            {
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `criminal_db`(`cid`, `cname`, `crime`, `age`, `phone`, `address`, `cdetail`) VALUES (?,?,?,?,?,?,?)";

                try {

                    ps = Get_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, cid);
                    ps.setString(2, cname);
                    ps.setString(3, crime);
                    ps.setString(4, age);
                    ps.setString(5, phone);
                    ps.setString(6, address);
                    ps.setString(7, cd);

                    // save the image as blob in the database

                    if(ps.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null, "criminal is added");
                    }else{
                        JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        

        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CriminalActionPerformed

    private void jTextField_addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addrActionPerformed

    private void jTextField_connoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_connoKeyTyped
if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
       }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_connoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criminal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criminal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criminal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criminal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criminal_details().setVisible(true);
            }
        });
    }
    
    public boolean verifyFields()
    {
      String cid = jTextField_cid.getText();
        String cname = jTextField_cname.getText();
       String crime = jTextField_ccrime.getText();
       String age = jTextField_age.getText();
       String phone = jTextField_conno.getText();
        String address = jTextField_addr.getText();
       String cd = jTextArea.getText();

        
        // check empty fields
        if(cid.trim().equals("") || cname.trim().equals("") || crime.trim().equals("")
           || age.trim().equals("") ||phone.trim().equals("")|| address.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
            return false;
        }
        else{
            return true;
        }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Criminal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField_addr;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_ccrime;
    private javax.swing.JTextField jTextField_cid;
    private javax.swing.JTextField jTextField_cname;
    private javax.swing.JTextField jTextField_conno;
    // End of variables declaration//GEN-END:variables
}

